### ISSUE TITLE
Bintray has been deprecated

### ISSUE THREAD

**Issue by bojanbabic** [linkedin/gdmix#20]
Instructions from README seem not to be correct. 

README contains a link to a [fat jar](https://linkedin.bintray.com/maven/com/linkedin/gdmix/gdmix-data-all_2.11/0.3.0/gdmix-data-all_2.11-0.3.0.jar) that gives 403. When looking at the [parent repo](https://bintray.com/linkedin/maven/gdmix-data-all/0.3.0), I get the message that the product has been deprecated. 

Please update README to the latest version.

**Comment by anjsam1402** [comment]
Any updates on this, as I have been facing the same issue.

**Comment by anjsam1402** [comment]
Just replace the sub-part of the jar link : [`https://linkedin.bintray.com/maven/`](https://linkedin.bintray.com/maven/) with [`https://linkedin.jfrog.io/artifactory/open-source/`](https://linkedin.jfrog.io/artifactory/open-source/).

Please update the README accordingly.

**Comment by junshi15** [comment]
Thank you. I have updated the README.
